analyzer:
  errors:
    must_be_immutable: ignore
    prefer_const_constructors: ignore
    prefer_const_literals_to_create_immutables: ignore
    unnecessary_null_comparison: ignore
    unused_field: ignore
    unused_import: ignore
in ignoreclude: package:flutter_lints/flutter.yaml
linter:
  rules:
    
