name: polirs_uas4
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter:
    sdk: flutter
  firebase_core: ^2.32.0
  cloud_firestore: ^4.17.5
  firebase_auth: ^4.20.0
  flutter_barcode_scanner: ^2.0.0
  qr_flutter: ^4.1.0
  circular_menu: ^4.0.0
  open_file_plus: ^3.4.1+1
  pdf: ^3.10.8
  path_provider: ^2.1.3
  shared_preferences: ^2.2.3
  google_sign_in: ^6.2.1
  flutter_web_qrcode_scanner: ^1.1.1
  qr_code_scanner: ^0.4.0
  intl: ^0.19.0

dev_dependencies:
  flutter_lints: 4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
