// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtws8l8Pt5a6r4CdAE4N16MXGdtcwvNUY',
    appId: '1:846947166017:web:a0eed96152a9babbb2e3c0',
    messagingSenderId: '846947166017',
    projectId: 'polirs-ca503',
    authDomain: 'polirs-ca503.firebaseapp.com',
    storageBucket: 'polirs-ca503.appspot.com',
    measurementId: 'G-PEJ2FDN7XY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnwm1vaLctj_jkFeno57ntrA6-eSYHexU',
    appId: '1:846947166017:android:0c2fdc4453278cefb2e3c0',
    messagingSenderId: '846947166017',
    projectId: 'polirs-ca503',
    storageBucket: 'polirs-ca503.appspot.com',
  );
}
